package com.codeinbp.bookappointment.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.codeinbp.bookappointment.utils.generateRandomAccessCode;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "appointment")
public class Appointment {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String appointmentId;   // should be partitionId from tables in aws dynamodb

    @DynamoDBAttribute
    private String firstName;

    @DynamoDBAttribute
    private String lastName;
    @DynamoDBAttribute
    private String dateOfBirth;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private String mobile;

    @DynamoDBAttribute
    private Date createdAt;

    @DynamoDBAttribute
    private Date updatedAt;

    @DynamoDBAttribute
    private Department department;

}
